verb=input("Please enter a verb ending in -ing")
adj=input("Please enter an adjective")
noun=input("Please enter a noun")
adverb=input("Please enter an adverb")
verb2=input("Please enter another verb ending in -ing")
adj2=input("Please enter another adjective")
noun2=input("Please enter another noun")
adverb2=input("Please enter another adverb")
print("One day a huge "+noun+" forcefully came "+verb+" into the "+adj+" "+noun2+". "+noun+" felt "+adverb+" for doing such a "+adj2+" thing. "+noun+" came "+verb2+" back towards "+noun2+" because he knew that "+noun2+" felt "+adverb2+" ")
